### ISSUE TITLE
Some of the courses with coupon are not signing up

### ISSUE THREAD

**Issue by mmohamedyaser** [AmmeySaini/Udemy-Paid-Courses-Grabber#10]
First of all nice project.👍
I am a security researcher too. We should keep in touch. 😉
Are you into **bug bounty**?
I found that some of the courses with the coupon are not signing up for me.
Not sure what the issue could be.
When I sign up for paid courses in my profile it always asks me to add the checkout details like country and state.
This could be one of the issue. 

![Executed command](https://user-images.githubusercontent.com/16500261/94170482-30caac80-fea1-11ea-839e-2174684f35dc.png)

![Browser page](https://user-images.githubusercontent.com/16500261/94170494-345e3380-fea1-11ea-95eb-d22543fd8d39.png)

**Comment by AmmeySaini** [comment]
Make sure that you aren't using any vpn. You need the same(country) ip with which you signed up the account. If you are signing up with US ip and logging with Indian in it won't work.

**Comment by mmohamedyaser** [comment]
Interesting. My account was created in UAE and I haven't used any VPN.
**I found the fix changing the currency to "USD" and currency symbol to "$" worked, in the payload parameter.**

Add it as a note to users in other countries. Helps a lot.

**Comment by AmmeySaini** [comment]
Yes as payloads are in Rupee and your account has prices in USD so it creates conflict.
