### ISSUE TITLE
INVALID HEADER VALUE [COOKIE METHOD]

### ISSUE THREAD

**Issue by maheleet** [AmmeySaini/Udemy-Paid-Courses-Grabber#11]
---->> Want to see available coupons (INPUT "n") OR subscribe to all available courses automatically (input "y"): y

------->> Discudemy <<-------

LOADING URLS: [■■■■□□□□□□]

[*] 1 Facebook Dynamic Ads (Facebook Dynamic Retargeting) MASTERYInvalid header value b'access_token=my access_token was here; client_id=my client_id was here with a \n'

please help to solve this error

**Comment by AmmeySaini** [comment]
Your cookie file format is not correct
Check readme for correct implementation

**Comment by maheleet** [comment]
I have do same like readme file, but no changes

**Comment by AmmeySaini** [comment]
For better understanding paste the content of your cookie file here. We can't help unless we get something to test upon

**Comment by maheleet** [comment]
ok i will send cookie file

**Comment by maheleet** [comment]
#cat cookie.txt 
Am6ZwIVzhw3zTyICWISw6cFlKBdOlmBlZmUrZ3Gy||bd2565cb7b0c313f5e9bae44961e8db2

this is my cookie file

**Comment by maheleet** [comment]
*] 1 [ Invideo ] Video Creation For Social Media Marketing Needs!https://www.udemy.com/course/invideo-video-creation-for-social-media-marketing-needs/?couponCode=CREATE_BEST_VIDEOS
Invalid header value b'access_token=Am6ZwIVzhw3zTyICWISw6cFlKBdOlmBlZmUrZ3Gy ; client_id= bd2565cb7b0c313f5e9bae44961e8db2\n'

unknown error


and i get this error

**Comment by AmmeySaini** [comment]
Was it working before or you got the error in very first attempt ?

**Comment by maheleet** [comment]
i get error in first attempt.....
can you help me or not?

**Comment by AmmeySaini** [comment]
I don't have any magic stick which will fix this thing i need to do proper debugging to reproduce this error and need to apply some fixes which will take time so, you just need to wait for further update on this

**Comment by maheleet** [comment]
ok ill wait

**Comment by iaman1998** [comment]
This is because your client id has a '\n' character, after you type in the client id do not press enter, simply save and close. If you're using echo to print to cookie_file then use echo -n
