### ISSUE TITLE
Please fix at this issue. This was wonderful script, Thank you.

### ISSUE THREAD

**Issue by Johanna007** [AmmeySaini/Udemy-Paid-Courses-Grabber#4]
C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py:734: **InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.** See: https://urllib3.readthedocs.org/en/latest/security.html

**Comment by AmmeySaini** [comment]
It has nothing to do with script
it seems like you are using some sniffing tools which is causing requests blockage due to SSl
Close all sniffing tools and retry

**Comment by Johanna007** [comment]
What do mean sniffing tools ?
