### ISSUE TITLE
Invalid Header Value Error

### ISSUE THREAD

**Issue by yashraj22** [AmmeySaini/Udemy-Paid-Courses-Grabber#5]
> hello@hello2-Vostro-3558:~/Udemy-Paid-Courses-Grabber$ python3 udemy.py -c cookie.txt
> 
>  _     _ _____   _______ ______  _     _     ______ ______  _   _ _ 
> | |   | (____ \ (_______)  ___ \| |   | |   / _____|_____ \( ) | | |
> | |   | |_   \ \ _____  | | _ | | |___| |  | /      _____) )/__| | |
> | |   | | |   | |  ___) | || || |\_____/   | |     |  ____//___)_|_|
> | |___| | |__/ /| |_____| || || |  ___     | \_____| |    |___ |_ _ 
>  \______|_____/ |_______)_||_||_| (___)     \______)_|    (___/|_|_|
> 
> [*] Trying to login with cookies! 
> 
> [*] Login Successful! 
> 
> [*] Websites Available: 
> Discudemy
> Udemy Freebies
> Udemy Coupons
> Real Discount
> Tricks Info
> Free Web Cart
> Course Mania
> Jojo Coupons
> Online Tutorials
> 
> ---->> Want to see available coupons (INPUT "n") OR subscribe to all available courses automatically (input "y"): y
> 
> ------->> Discudemy <<-------
> 
> LOADING URLS: [■■■■□□□□□□]
> 
> [*] 1 Facebook Dynamic Ads (Facebook Dynamic Retargeting) MASTERYInvalid header value b'access_token=my access_token was here; client_id=my client_id was here with a \n'
> 
> unknown error
> yashraj@yashraj-Vostro-3558:~/Udemy-Paid-Courses-Grabber$ 

**for some reason '\n' is getting appended at last of client_id's  value inside cookies dictionary, When I used a line of code (provided below) to remove that '\n' from client_id's value everything worked fine**

    `cookies['client_id'] = cookies['client_id'].strip('\n')`

I added this code below https://github.com/AmmeySaini/Udemy-Paid-Courses-Grabber/blob/master/udemy.py#L250 in file udemy.py

**Comment by AmmeySaini** [comment]
your cookie.txt file is not in right format

**Comment by yashraj22** [comment]
@AmmeySaini I rechecked it correctly it was fine

**Comment by AmmeySaini** [comment]
Closing this as no response for your end. You can open this anytime later.
