### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by chaoscreater** [AmmeySaini/Udemy-Paid-Courses-Grabber#6]
Hi there,

Let's say I already have a list of Udemy courses with coupons from this website below:
https://yofreesamples.com/courses/free-discounted-udemy-courses-list/

The URLs can be stored in a .txt file. I would like to use your script to automatically enroll in those courses. Is that possible?

**Comment by AmmeySaini** [comment]
Yep, might add with a new update
