### ISSUE TITLE
Enhancement: username password file instead of cookie file

### ISSUE THREAD

**Issue by isurukdniss** [AmmeySaini/Udemy-Paid-Courses-Grabber#7]
Hi,
Appreciate if you can add the ability to run the script by providing username and password from an input file. Every time we need to run the script we have to log in to the Udemy account update the access token in the cookie file. 

If we can run with username and password, this can be automated very easily.

Thanks!

**Comment by AmmeySaini** [comment]
There is already an automatic login feature available. You just need to login in your chrome or firefox browser and run the script normally and it'll automatically log you in
