### ISSUE TITLE
most of the sources after discudemy aren't working

### ISSUE THREAD

**Issue by dakar111** [AmmeySaini/Udemy-Paid-Courses-Grabber#9]
After discudemy almost all the other websites get passed through and have no results/aren't working properly(you just see the total course number on every line) ; then the script just closes.

My suggestion:

Keep: discudemy
Add: https://yofreesamples.com/courses/free-discounted-udemy-courses-list/
Remove all the rest.

The above 2 websites together will rarely miss any coupon.

**Comment by AmmeySaini** [comment]
You can remove websites your self which u don't like by simply editing bunch of lines in code
